name: Basic Checks

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  python-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl openai pytest
    
    - name: Run basic syntax check
      run: |
        python -m py_compile main.py
        python -m py_compile core/*.py
        python -m py_compile workflows/*/*.py
    
    - name: Run basic import test
      run: |
        python -c "from core.data_processor import DataProcessor; print('✅ Core imports successful')"
        python -c "from workflows.contact_export.export_processor import ExportProcessor; print('✅ Workflow imports successful')"
    
    - name: Run basic tests
      run: |
        python -m pytest tests/ -v --tb=short || echo "Some tests failed but continuing..."
